### ISSUE TITLE
auto deployed storage name 

### ISSUE THREAD

**Issue by yodobrin** [csu-devsquad-latam/trunkbased-mlops#8]
the auto created storage account (for the workspace) is derived from the workspace name. 
this is defined in workspace.json line ~23:
"defaultValue": "[replace(parameters('workspaceName'),'-', '')]",

Now since the workspace name is not globally (it has resource group scope) unique and the storage is, unless you give unique name to the workspace, you might fail creating the storage. 
https://docs.microsoft.com/en-us/azure/azure-resource-manager/management/resource-name-rules

**Comment by santiagxf** [comment]
This is a really good point. For simplicity, we decided to automatically name the elements for the user. However, since not all of the have the same scope it may create collisions. We can address this with documentation but wondering what's your opinion around that.

**Comment by yodobrin** [comment]
I can create a PR to address this. I agree that documentation with brief explanation is a quick fix. we can also use random value for the name of the storage (as done when creating aml from the portal), or add another parameter.

**Comment by yodobrin** [comment]
I am having an issue creating a pr, but this is the fix to the workspace.json line 23
"defaultValue": "[concat('sa', uniqueString(replace(parameters('workspaceName'),'-', '')))]",

I verified it. it creates names like: "sakq74hk6d6jzx6"

**Comment by santiagxf** [comment]
Random names don't seem to be the right approach from a maintainability perspective. That's the reason why we named storage accounts in the same way workspaces are.

**Comment by yodobrin** [comment]
got it, what about a concat of the workspace name with four random characters?

**Comment by santiagxf** [comment]
Usually, enterprises are against naming things randomly. We usually suggest appending something in the name that will ensure it is unique. For instance, if the organization is "Contoso" and they use a naming convention like "<org>-<application>-<resource-type>-<env>" then it will produce names like "cnt-trunkbased-ws-dev", where:

- cnt = Contoso
- trunkbased = Application
- ws = Machine Learning Workspace
- dev =  Development environment.

Since storage accounts don't allow dashes on the name, they will translate to "cnttrunkbasedsadev". But the same convention applies and this is usually something that the Cloud Governance team in the organization controls to ensure compliance.

**Comment by santiagxf** [comment]
Closed due to inactivity.
